version: "3.7"

services:

  laravue-app-php:
    build:
      args:
        user: ${APP_USER}
        uid: 1000
      context: ./
      dockerfile: docker/php/Dockerfile
    container_name: laravue-app-php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravue-app-network

  laravue-app-server:
    image: nginx:alpine
    container_name: laravue-app-server
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - laravue-app-network

  laravue-app-storage:
    image: mysql:5.7
    container_name: laravue-app-storage
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravue-app-network

  laravue-app-nodejs:
    image: node:13-alpine
    container_name: laravue-app-nodejs
    restart: unless-stopped
    working_dir: /var/www/
    command: sh -c "npm install"
    volumes:
      - ./:/var/www
      - ./node_modules:/var/www/node_modules
    networks:
      - laravue-app-network

networks:
  laravue-app-network:
    driver: bridge
